//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdaNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdaNet.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find calling assembly..
        /// </summary>
        internal static string CantFindCallingAssembly {
            get {
                return ResourceManager.GetString("CantFindCallingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to save database to &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseFailedToSave {
            get {
                return ResourceManager.GetString("DatabaseFailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load &apos;{0}&apos; file..
        /// </summary>
        internal static string FileLoadFailed {
            get {
                return ResourceManager.GetString("FileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is invalid until a database has been opened..
        /// </summary>
        internal static string NoDatabase {
            get {
                return ResourceManager.GetString("NoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Guid attribute could be found on calling assembly &apos;{0}&apos;..
        /// </summary>
        internal static string NoGuidFoundOnCallingAssembly {
            get {
                return ResourceManager.GetString("NoGuidFoundOnCallingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Guid attribute found on IdaNet assembly..
        /// </summary>
        internal static string NoGuidFoundOnIdaNet {
            get {
                return ResourceManager.GetString("NoGuidFoundOnIdaNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loader could be found for file &apos;{0}&apos;..
        /// </summary>
        internal static string NoLoaderFound {
            get {
                return ResourceManager.GetString("NoLoaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected loader returned by the loader chooser is not a known loader..
        /// </summary>
        internal static string SelectedLoaderNotGenuine {
            get {
                return ResourceManager.GetString("SelectedLoaderNotGenuine", resourceCulture);
            }
        }
    }
}
