using System;

namespace IdaNet.IdaInterop
{
    [Flags()]
    internal enum AsciiFlags : byte
    {
        ASCF_GEN = 0x01,            //   generate ASCII names?
        ASCF_AUTO = 0x02,            //   ASCII names have 'autogenerated' bit?
        ASCF_SERIAL = 0x04,            //   generate serial names?
        ASCF_UNICODE = 0x08,            //   unicode strings are present?
        ASCF_COMMENT = 0x10,            //   generate auto comment for ascii references?
        ASCF_SAVECASE = 0x20,            //   preserve case of ascii strings for identifiers
    }
}
