using System;

namespace IdaNet.IdaInterop
{
    [Flags()]
    internal enum ListNameFlags : byte
    {
        LN_NORMAL = 0x01,            //   normal names
        LN_PUBLIC = 0x02,            //   public names
        LN_AUTO = 0x04,            //   autogenerated names
        LN_WEAK = 0x08,            //   weak names
    }
}
